# p3/confs/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd          # must be in argocd namespace
spec:
  project: default

  source:
    repoURL: https://github.com/HKEV07/inception-of-things.git
    targetRevision: main
    path: P3/confs            # Argo CD looks for manifests here

  destination:
    server: https://kubernetes.default.svc
    namespace: dev            # deploy into the dev namespace

  syncPolicy:
    automated:
      prune: true             # delete resources removed from Git
      selfHeal: true          # re-apply if someone manually changes the cluster
    syncOptions:
      - CreateNamespace=true  # create 'dev' if it doesn't exist
