apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inception-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HKEV07/inception-of-things.git
    targetRevision: main
    path: P3/confs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
